package com.sokhibdzhon.livedota.buildsrc

object Versions {
    const val crashlyticsVersion = "17.1.1"
    const val gmsGoogleServies = "4.3.3"
    const val firebaseVersion = "17.4.4"
    const val kotlinVersion = "1.3.72"
    const val roomVersion = "2.2.5"
    const val roomKtxVersion = "2.2.5"
    const val gsonVersion = "2.8.6"
    const val loggingInterceptorVersion = "4.0.1"
    const val navVersion = "2.2.2"
    const val daggerVersion = "2.26"
    const val retrofitVersion = "2.6.1"
    const val lifecycleVersion = "2.2.0"
    const val coroutineVersion = "1.3.4"
    const val gradleVersion = "3.6.3"
    const val appcompatVersion = "1.1.0"
    const val gradleCrashlyticsVersion = "2.2.0"
    const val coreKtxVersion = "1.2.0"
    const val constraintLayoutVersion = "1.1.3"
    const val legacySupportV4Version = "1.0.0"
    const val junitVersion = "4.12"
    const val materialVersion = "1.1.0"
    const val androidXTestJUnitVersion = "1.1.1"
    const val androidXTestEspressoCoreVersion = "3.2.0"
    const val timberVersion = "4.7.1"
    const val glideVersion = "4.11.0"
    const val debugDbVersion = "1.0.6"
}